### ISSUE TITLE
Where are you get APIs from? 

### ISSUE THREAD

**Issue by YehudaCorsia** [pieewiee/CiscoPrimeMapExport#2]
Hey, I would like to know where are you get the APIs from?

Because I can't see them in the official docs

**Comment by pieewiee** [comment]
There are actually two APIs for Cisco Prime

The official customer API:
https://solutionpartner.cisco.com/media/prime-infrastructure/api-reference/szier-m8-106.cisco.com/webacs/api/v1/index.html

The "Webinterface" itself (used by this script):
Here is no documentation available, but the best way is to use the webbrowser's develolper tools in order to get a better understanding of the web requests.

have a look at the config/config.json file. here are the urls written. 

modules/webrequest.psm1 <-- Webrequest functions

**Comment by YehudaCorsia** [comment]
Interesting

But why you don't use this two official APIs?

https://developer.cisco.com/site/prime-infrastructure/documents/api-reference/rest-api-v3-8/v4/op/maps/%7BmapId%7D/image-GET@_docs/

https://developer.cisco.com/site/prime-infrastructure/documents/api-reference/rest-api-v3-8/v4/data/ServiceDomains@_docs/

**Comment by pieewiee** [comment]
i already created a map export for previous cisco prime versions and i havn't seen that this is now possible :-) 

thank you! i will give it a try!

**Comment by pieewiee** [comment]
solved
